sensor:
  - name: "oPMs Temperature json" 
    state_topic: "topic/temperature"
    unit_of_measurement: "°C"
    value_template: "{{ value_json.temperature }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Humidity json"
    state_topic: "topic/humidity"
    unit_of_measurement: " %"
    value_template: "{{ value_json.humidity }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Temperature value" 
    state_topic: "opms/temperature"
    unit_of_measurement: "°C"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Humidity value"
    state_topic: "opms/humidity"
    unit_of_measurement: " %"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Dew Point" 
    state_topic: "opms/dew point"
    unit_of_measurement: "°C"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs barometric pressure" 
    state_topic: "opms/barometric pressure"
    unit_of_measurement: "atm"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Mass Density PM1.0" 
    state_topic: "opms/pm1.0"
    unit_of_measurement: "ug/m3"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Mass Density PM2.5" 
    state_topic: "opms/pm2.5"
    unit_of_measurement: "ug/m3"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Mass Density PM10" 
    state_topic: "opms/pm10"
    unit_of_measurement: "ug/m3"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Mass Density PM1.0 SPS30" 
    state_topic: "opms/pm1.0_ch2"
    unit_of_measurement: "ug/m3"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Mass Density PM2.5 SPS30" 
    state_topic: "opms/pm2.5_ch2"
    unit_of_measurement: "ug/m3"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Mass Density PM10 SPS30" 
    state_topic: "opms/pm10_ch2"
    unit_of_measurement: "ug/m3"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"
  - name: "oPMs Mass Density PM4 SPS30" 
    state_topic: "opms/pm4_ch2"
    unit_of_measurement: "ug/m3"
    json_attributes_template: "{{ value }}"
    payload_available: "online"
    payload_not_available: "offline"