BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "measurements" (
	"id"	INTEGER,
	"station"	INTEGER NOT NULL,
	"datetime"	TEXT NOT NULL,
	"humidity"	NUMERIC NOT NULL,
	"temperature"	NUMERIC NOT NULL,
	"pm1.0"	NUMERIC NOT NULL,
	"pm2.5"	NUMERIC NOT NULL,
	"pm4"	NUMERIC,
	"pm10"	NUMERIC,
	"pm1.0_ch2"	NUMERIC,
	"pm2.5_ch2"	NUMERIC,
	"pm4_ch2"	NUMERIC,
	"pm10_ch2"	NUMERIC,
	"sound pressure"	INTEGER,
	"barometric pressure"	NUMERIC,
	"battery charge percentage"	NUMERIC,
	"vsys voltage"	NUMERIC,
	"internal temperature"	NUMERIC,
	"wind direction"	INTEGER,
	"wind speed"	INTEGER,
	"battery is charging"	INTEGER,
	"dew point"	NUMERIC,
	"vehicles"	INTEGER,
	"latitude"	NUMERIC,
	"longitude"	NUMERIC,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "stations" (
	"id"	INTEGER,
	"name"	TEXT NOT NULL,
	"maintainer"	TEXT NOT NULL,
	"station purpose"	TEXT NOT NULL,
	"latitude"	NUMERIC NOT NULL DEFAULT 0,
	"longitude"	NUMERIC NOT NULL DEFAULT 0,
	"altitude msl"	INTEGER,
	"country"	TEXT NOT NULL,
	"city"	TEXT NOT NULL,
	"address"	TEXT NOT NULL,
	"pm capable ch1"	INTEGER NOT NULL DEFAULT 0,
	"pm capable ch2"	INTEGER NOT NULL DEFAULT 0,
	"pm units ch1"	TEXT NOT NULL DEFAULT 'ug/m^3',
	"pm units ch2"	TEXT DEFAULT 'ug/m^3',
	"pm sensor model ch1"	TEXT NOT NULL,
	"pm sensor model ch2"	TEXT,
	"pm sensor SN ch1"	TEXT,
	"pm sensor SN ch2"	TEXT,
	"pm sensor in situ calibration report ch1"	TEXT,
	"pm sensor in situ calibration report ch2"	TEXT,
	"pm sensor uncertainty percentage ch1"	INTEGER,
	"pm sensor uncertainty percentage ch2"	INTEGER,
	"sound pressure capable"	INTEGER NOT NULL DEFAULT 0,
	"sound pressure units"	TEXT,
	"sound pressure sensor model"	TEXT,
	"barometric pressure capable"	INTEGER NOT NULL DEFAULT 0,
	"barometric pressure units"	TEXT DEFAULT 'hPa',
	"barometric pressure sensor model"	TEXT,
	"temperature capable"	INTEGER NOT NULL DEFAULT 0,
	"temperature units"	TEXT DEFAULT '°C',
	"temperature sensor model"	TEXT,
	"vehicle count capable"	INTEGER NOT NULL DEFAULT 0,
	"vehicle count units"	TEXT,
	"vehicle sensor model"	TEXT,
	"wind direction capable"	INTEGER NOT NULL DEFAULT 0,
	"wind direction units"	TEXT DEFAULT '°',
	"wind direction sensor model"	TEXT,
	"wind speed capable"	INTEGER NOT NULL DEFAULT 0,
	"wind speed units"	TEXT DEFAULT 'm/s',
	"wind speed sensor model"	TEXT,
	"humidity capable"	INTEGER NOT NULL DEFAULT 0,
	"humidity units"	TEXT DEFAULT '%',
	"humidity sensor model"	TEXT,
	"height above ground"	INTEGER,
	"height above ground units"	TEXT DEFAULT 'cm',
	"rover"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);
COMMIT;
